export const checkedOrdersActionTypes = {
    SET_CHECKED_ORDERS: "GROUP_ACTIONS.SET_CHECKED_ORDERS",
    DELETE_CHECKED_ORDERS: "GROUP_ACTIONS.DELETE_CHECKED_ORDERS",
    CLEAR_CHECKED_ORDERS: "GROUP_ACTIONS.CLEAR_CHECKED_ORDERS",
    SET_ALL_CHECKED_ORDERS: "GROUP_ACTIONS.SET_ALL_CHECKED_ORDERS",
};

export const paginationActionTypes = {
    SET_CURRENT_PAGE: "PAGINATION.SET_CURRENT_PAGE",
};

export const sortedActionTypes = {
    SORTED: "FILTERS.SORTED",
    REFRESH: "FILTERS.REFRESH",
};

export const statusesActionTypes = {
    SET_STATUSES: "FILTERS.SET_STATUSES",
    CLEAR_STATUSES: "FILTERS.CLEAR_STATUSES",
};