export const ordersActionTypes = {
    SET_ORDERS: "ORDERS.SET_ORDERS",
    CHANGE_ORDER_STATUS: "ORDERS.CHANGE_ORDER_STATUS",
    CHANGE_ORDER_NAME: "ORDERS.CHANGE_ORDER_NAME",
    SEARCH_ORDERS: "ORDERS.SEARCH_ORDERS",
    SORT_ORDERS: "ORDERS.SORT_ORDERS",
    DELETE_CHECKED_ORDERS: "ORDERS.DELETE_CHECKED_ORDERS",
    FILTER_ORDERS_BY_DATE: "ORDERS.FILTER_ORDERS_BY_DATE",
    FILTER_ORDERS_BY_SUM: "ORDERS.FILTER_ORDERS_BY_SUM",
    FILTER_ORDERS_BY_STATUS: "ORDERS.FILTER_ORDERS_BY_STATUS",
    FILTER_ORDERS: "ORDERS.FILTER_ORDERS",
    CHANGE_GROUP_STATUS: "ORDERS.CHANGE_GROUP_STATUS",
    RESET_ORDERS: 'ORDERS.RESET'
};